### ISSUE TITLE
Custom Signed Extensions

### ISSUE THREAD

**Issue by justkawal** [leonardocustodio/polkadart#359]

**Comment by clangenb** [comment]
I see you have assigned this to yourself, may I ask when you intend to implement this?

**Comment by leonardocustodio** [comment]
Id everything goes as planned I was hoping to finish this by the end of the month

**Comment by clangenb** [comment]
As usual, thanks a lot for your quick reply. This helps a lot with planing! 😊

**Comment by leonardocustodio** [comment]
I've unsigned myself as @justkawal has already made some progress on this, we should have the PR really soon.

**Comment by leonardocustodio** [comment]
Released under:
```
polkadart: ^0.4.0
polkadart_scale_codec: ^1.2.0
substrate_metadata: ^1.2.0
```
