### ISSUE TITLE
Can't use `sr25519` `Error: Member not found: 'sr25519'.`

### ISSUE THREAD

**Issue by AlaaElattar** [leonardocustodio/polkadart#370]
``` dart
void main() async {
  final polkadart = Provider.fromUri(Uri.parse('wss://tfchain.dev.grid.tf/ws'));
  final keyring = Keyring();
  final mnemonic =
      "secret add bag cluster deposit beach illness letter crouch position rain arctic";
final seed = await SubstrateBip39.sr25519.seedFromUri(mnemonic);
  final address = KeyPair.fromSeed(Uint8List.fromList(seed)).address;
  print(address);
  await polkadart.disconnect();
}
```

I'm trying to load sr25519 according to this example https://github.com/leonardocustodio/polkadart/tree/main/packages/substrate_bip39 but getting the error :
```
bin/tfgrid_sdk_dart.dart:16:35: Error: Member not found: 'sr25519'.
final seed = await SubstrateBip39.sr25519.seedFromUri(mnemonic);
```

**Comment by leonardocustodio** [comment]
Hello, that example should not be there. We don't support sr25519 yet. There is no crypto lib for that algorithm in dart yet and we will have to build it. It will take a bit of time yet so we can support it.

**Comment by leonardocustodio** [comment]
I've changed the readme and deleted that part until we can support it.

**Comment by leonardocustodio** [comment]
Just in case someone finds this issue we now support sr25519.
