### ISSUE TITLE
Wrong storage hash key for storage value

### ISSUE THREAD

**Issue by clangenb** [leonardocustodio/polkadart#373]
In our generated code we have this:

```dart
  final _i1.StorageValue<int> _endorsementTicketsPerBootstrapper = const _i1.StorageValue<int>(
    prefix: 'EncointerCeremonies',
    storage: 'EndorsementTicketsPerBootstrapper',
    valueCodec: _i4.U8Codec.codec,
  );
```

The generated key hash:

```
    final hashedKey = _endorsementTicketsPerBootstrapper.hashedKey();

    // hashedKey: 0xa7d291a8132b2cc65c41da45f4de76796ae3d97cb4a9938c6ebddc6491b5bc06
    print("hashedKey: 0x${hex.encode(hashedKey)}");
```

Is wrong, the correct key hash according to polkadot-js/apps is:

![image](https://github.com/leonardocustodio/polkadart/assets/37865735/0ec2ee7d-d2f3-4885-a5f3-7852de44292d)

So the method is wrong in this case, whereas the prefix is correct. The method has 33 characters, so my guess is that some magic happens on substrate side for prefixes > 32 bytes.

**Comment by leonardocustodio** [comment]
Ok, found the issue it is in the xxh64 algorithm actually (that is used by twox). cc @justkawal

**Comment by leonardocustodio** [comment]
Fixed on version `0.2.4`

**Comment by clangenb** [comment]
I can confirm that it is fixed on our end. Thanks for the blazingly fast fix!

**Comment by clangenb** [comment]
I have to correct my statement, the hash seems to be wrong in other cases now, example:

```dart
  final _i1.StorageValue<_i3.CeremonyPhaseType> _currentPhase = const _i1.StorageValue<_i3.CeremonyPhaseType>(
    prefix: 'EncointerScheduler',
    storage: 'CurrentPhase',
    valueCodec: _i3.CeremonyPhaseType.codec,
  );

// wrong result: 
// 26dc3fa0a77526a8494180a4789f6883d9764401941df7f77a47ba7db64a6e0a
// actual value:
// 26dc3fa0a77526a8494180a4789f6883d9764401941df7f707a47ba7db64a6ea
```

Actual value: 

![image](https://github.com/leonardocustodio/polkadart/assets/37865735/4fd491b6-ef79-45d6-b1f1-113ae906de9d)

It only seems to affect the last bytes.

**Comment by clangenb** [comment]
It seems I can't reopen the issue unfortunately. Shall I create a new one?

**Comment by leonardocustodio** [comment]
They are pretty close though haha. Seems people are not really good at making hashing algorithms. I wish dart itself had them. I will check it later.

**Comment by leonardocustodio** [comment]
Totally my fault this one. When converting to hex it did not use signed 2's complement. It should be fixed now, also added this string to the tests.

**Comment by leonardocustodio** [comment]
Released under version:
polkadart: ^0.2.5

**Comment by clangenb** [comment]
Nice, our integration tests work again, seems to be fine, thanks a lot for this quick reaction again! 👍
