### ISSUE TITLE
Build failed with an exception.

### ISSUE THREAD

**Issue by StepanUsynin** [leonardocustodio/polkadart#383]
Greetings! First of all, thank you very much for the package, I really hope it will continue to be supported.

I came across a problem. If I generate code for networks that have smart contracts module, I get the following error when building the project

lib/generated/astar/pallets/contracts.dart:432:36: Error: The method 'call' isn't defined for the class '$Call'.
 - '$Call' is from 'package:polkadart_test/generated/astar/types/pallet_contracts/pallet/call.dart' ('lib/generated/astar/types/pallet_contracts/pallet/call.dart').
Try correcting the name to the name of an existing method, or defining a method named 'call'.
    final _call = _i12.Call.values.call(
                                   ^^^^
lib/generated/astar/pallets/evm.dart:153:35: Error: The method 'call' isn't defined for the class '$Call'.
 - '$Call' is from 'package:polkadart_test/generated/astar/types/pallet_evm/pallet/call.dart' ('lib/generated/astar/types/pallet_evm/pallet/call.dart').
Try correcting the name to the name of an existing method, or defining a method named 'call'.
    final _call = _i9.Call.values.call(
                                  ^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

network from pub spec yaml:
polkadart:
  output_dir: lib/generated
  chains: 
    Astar: wss://astar.public.blastapi.io

**Comment by leonardocustodio** [comment]
Can you provide us the version of the packages/dart/flutter and which platform (web, mobile, desktop)?

**Comment by StepanUsynin** [comment]
- Dart 3.2.3 (stable) (Tue Dec 5 17:58:33 2023 +0000) on "macos_arm64"

[✓] Flutter (Channel stable, 3.16.4, on macOS 14.0 23A344 darwin-arm64, locale en-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
[✓] IntelliJ IDEA Community Edition (version 2023.2.5)
[✓] VS Code (version 1.85.1)
[✓] Connected device (5 available)
[✓] Network resources

environment:
  sdk: '>=3.0.0 <4.0.0'

 polkadart: ^0.2.6
 polkadart_cli: ^0.2.4
 polkadart_keyring: ^0.2.1
 polkadart_scale_codec: ^1.1.2
 ss58: ^1.1.2
 substrate_bip39: ^0.2.0
 substrate_metadata: ^1.1.2

polkadart:
  output_dir: lib/generated 
  chains: 
    Astar: wss://astar.public.blastapi.io

Tried to run on iOS and Android platforms.
But actually the platform doesn't matter. This is a compile time error.

**Comment by leonardocustodio** [comment]
Do you think you can take a look @justkawal ? I've no computer access for the next 3 days.

**Comment by leonardocustodio** [comment]
Hello @StepanUsynin, sorry as you can imagine I was on holidays. You are correct it seems `polkadart_cli` doesn't work with Astar, probably something related with the EVM support. I will check that during the weekend.

**Comment by leonardocustodio** [comment]
We have relead v0.3.1 of `polkadart_cli` with a fix for this. Thank you for your report.
