### ISSUE TITLE
Runtime Api calls

### ISSUE THREAD

**Issue by StepanUsynin** [leonardocustodio/polkadart#399]
The Polkadot.js library has the ability to call Runtime Api methods, 

here's a link to the doc https://polkadot.js.org/docs/substrate/runtime/#accountnonceapi

Can you please tell me if it is possible to call such methods in this library?

**Comment by leonardocustodio** [comment]
I believe all runtime calls can be called through a `state call` here you can find a sample of the payload sent to the RPC: 

```json
{"id":35,"jsonrpc":"2.0","method":"state_call","params":["AccountNonceApi_account_nonce","0xbc068bc168aeb8e22637617e56f8c819ff2f16c49f00af5ee00a116a30397910"]}
```

An example of doing that in polkadart would be:
```dart
 
final provider = Provider.fromUri(Uri.parse('wss://rpc.matrix.canary.enjin.io'));
final api = Polkadot(provider);
final stateApi = StateApi(provider);
final stateCall = await stateApi.call(
      'AccountNonceApi_account_nonce',
      decodeHex(
          '0xbc068bc168aeb8e22637617e56f8c819ff2f16c49f00af5ee00a116a30397910')
);
print(stateCall);
```

**Comment by StepanUsynin** [comment]
Just what is needed, grateful for that!

**Comment by leonardocustodio** [comment]
You are welcome
