### ISSUE TITLE
Transaction to an address in string

### ISSUE THREAD

**Issue by web3-sante** [leonardocustodio/polkadart#420]
Hello team,
dumb question here:

How to execute a simple transfer to an address in this format 
```dart
    final BOB = '5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty';
```
without also having to grab infos like  [block hash, genesis...](https://github.com/leonardocustodio/polkadart/blob/main/examples/bin/extrinsic_demo.dart) but just something in this [style](https://polkadot.js.org/docs/api/examples/promise/make-transfer).

What would be the best way or place to ask questions without having to open issues?

**Comment by leonardocustodio** [comment]
Hello @web3-sante, right now, that's not possible. We started this project last year and there is a lot to be done yet. We are first working on supporting everything Polkadot can do, after that when people can do everything (in a harder or easier way) then we will start to work in the helpers and things to reduce the boilerplates. Feel free to send PR's if you make something and would like to contribute. And for now, issues here are the best (and only place), so no worries.

**Comment by morgueye4** [comment]
Thanks @leonardocustodio for the reply. Sure if I do something I'll make the PR!
