### ISSUE TITLE
After using the private key to sign the data, the array length in R is 32, and the first element appears 0. How should I solve this problem?

### ISSUE THREAD

**Issue by querli** [leonardocustodio/polkadart#422]
<img width="1569" alt="image" src="https://github.com/leonardocustodio/polkadart/assets/45426897/e744b787-aedc-4b2c-929c-086aaf453207">

**Comment by leonardocustodio** [comment]
@justkawal

**Comment by justkawal** [comment]
Looking into it.

> @justkawal

**Comment by justkawal** [comment]
Can you share your intToBytes function ?

> <img alt="image" width="1569" src="https://private-user-images.githubusercontent.com/45426897/306618507-e744b787-aedc-4b2c-929c-086aaf453207.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NDU1NDksIm5iZiI6MTcwODU0NTI0OSwicGF0aCI6Ii80NTQyNjg5Ny8zMDY2MTg1MDctZTc0NGI3ODctYWVkYy00YjJjLTkyOWMtMDg2YWFmNDUzMjA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDE5NTQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmZDRmYzE5MjFlMjQyNDc4MGU3OTgwNmMzZjE1YzVkZTBhYTIxY2I4MzYzYzQ2YTI4ZmM3OWU5YzM0Zjg5NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W-UR23DtuVUEu9XtlhdP4gjUUM3ChbnQcd34Uk61RoY">

**Comment by justkawal** [comment]
On my side I used the internal Utilities class methods to convert the `BigInt` to `Bytes`.

<img width="1081" alt="Screenshot 2024-02-21 at 14 58 49" src="https://github.com/leonardocustodio/polkadart/assets/49296873/2dd6dce9-1d48-4633-8ff0-c6e61f1b6e30">

**Comment by justkawal** [comment]
@querli I haven't done the `Hash.hashSHA256` on line 6 because sign function does that internally already on calling `sign` method:

https://github.com/leonardocustodio/polkadart/blob/592ec4344e94e3bdcb7de6616d1212ff3b812c7c/packages/secp256k1_ecdsa/lib/src/private_key.dart#L56

**Comment by querli** [comment]
Thank you very much for your answer? Is now positioning is intToBytes function problem, use the library is web3dart 2.7.2, link is https://pub.dev/packages/web3dart, due to the cognition is not deep, specific don't know what is the difference between transformation!

**Comment by leonardocustodio** [comment]
Hey @querli, not sure I understood your comment. You mean you were using another lib to make the convertion? But did your problem get solved now?

**Comment by querli** [comment]
Yes, I used the web3Dart library. Since secp256K1 cannot be used, I relied on your secp256k1_ecdsa separately. Now I use secp256k1_ecdsa to convert the data format

**Comment by querli** [comment]
> hmacSha256

Is this optional parameter hmacSha256 also a sha256 hash function? What if you use it?

**Comment by querli** [comment]
May I ask whether recovery in Signature can control the automatic addition of 27? Make recovery 27 or 28
