### ISSUE TITLE
[question] any plan to add sr25519 support on substrate_bip39?

### ISSUE THREAD

**Issue by gtmickey** [leonardocustodio/polkadart#448]
I want to get seed and store on localdb rather than store user's mnemonic. I saw substrate_bip39 can get seed from api. but no sr25519 support. 
Keyring support sr25519, but keyring made _seed as private value, cannot get it.

**Comment by leonardocustodio** [comment]
@justkawal can you check this one?

**Comment by justkawal** [comment]
@gtmickey Sorry for late reponse.

I guess you could get the seed with: 
```dart
final List<int> seed = await KeyPair.sr25519.seedFromUri('your mnemonic uri');
```
