### ISSUE TITLE
Flutter  3.22.0 version solving failed

### ISSUE THREAD

**Issue by StepanUsynin** [leonardocustodio/polkadart#453]
In the new version of Flutter, pub get throws an error

Because json_schema2 >=2.0.2+9 <2.0.2+10 depends on rest_client ^2.1.5 and json_schema2 >=2.0.2+10 <2.0.2+11 depends on rest_client ^2.1.5+1, json_schema2 >=2.0.2+9 <2.0.2+11 requires rest_client ^2.1.5.
And because json_schema2 >=2.0.2+11 <2.0.2+12 depends on rest_client ^2.1.5+2, json_schema2 >=2.0.2+9 <2.0.2+12 requires rest_client ^2.1.5.
And because json_schema2 >=2.0.2+12 <2.0.2+13 depends on rest_client ^2.1.5+3 and json_schema2 >=2.0.2+13 <2.0.2+14 depends on rest_client ^2.1.5+4, json_schema2 >=2.0.2+9 <2.0.2+14 requires rest_client ^2.1.5.
And because json_schema2 >=2.0.2+14 <2.0.2+15 depends on rest_client ^2.1.5+5 and json_schema2 >=2.0.2+15 <2.0.2+16 depends on rest_client ^2.2.0, json_schema2 >=2.0.2+9 <2.0.2+16 requires rest_client ^2.1.5.
And because json_schema2 >=2.0.2+16 <2.0.2+17 depends on rest_client ^2.2.0+1 and json_schema2 >=2.0.2+17 <2.0.2+18 depends on rest_client ^2.2.0+2, json_schema2 >=2.0.2+9 <2.0.2+18 requires rest_client ^2.1.5.
And because json_schema2 >=2.0.2+18 <2.0.2+19 depends on rest_client ^2.2.0+3 and json_schema2 >=2.0.2+19 <2.0.2+20 depends on rest_client ^2.2.0+6, json_schema2 >=2.0.2+9 <2.0.2+20 requires rest_client ^2.1.5.
And because json_schema2 >=2.0.2+20 <2.0.2+21 depends on rest_client ^2.2.0+7 and json_schema2 >=2.0.2+21 <2.0.3+1 depends on rest_client ^2.2.0+8, json_schema2 >=2.0.2+9 <2.0.3+1 requires rest_client ^2.1.5.
And because json_schema2 >=2.0.3+1 <2.0.3+2 depends on rest_client ^2.2.1+1 and json_schema2 >=2.0.3+2 <2.0.3+3 depends on rest_client ^2.2.1+2, json_schema2 >=2.0.2+9 <2.0.3+3 requires rest_client ^2.1.5.
And because json_schema2 >=2.0.3+3 <2.0.3+4 depends on rest_client ^2.2.1+3 and json_schema2 >=2.0.3+4 <2.0.3+5 depends on rest_client ^2.2.1+4, json_schema2 >=2.0.2+9 <2.0.3+5 requires rest_client ^2.1.5.
And because json_schema2 >=2.0.3+5 <2.0.3+6 depends on rest_client ^2.2.1+5 and json_schema2 >=2.0.3+6 <2.0.3+7 depends on rest_client ^2.2.1+6, json_schema2 >=2.0.2+9 <2.0.3+7 requires rest_client ^2.1.5.
And because json_schema2 >=2.0.3+7 <2.0.4+1 depends on rest_client ^2.2.1+7 and json_schema2 >=2.0.4+1 <2.0.4+2 depends on rest_client ^2.2.1+8, json_schema2 >=2.0.2+9 <2.0.4+2 requires rest_client ^2.1.5.
And because json_schema2 >=2.0.4+4 <5.1.2 depends on rest_client ^2.2.1+11 and json_schema2 >=2.0.4+3 <2.0.4+4 depends on rest_client ^2.2.1+10, json_schema2 >=2.0.2+9 <2.0.4+2 or >=2.0.4+3 <5.1.2-∞ requires rest_client ^2.1.5.
And because json_schema2 >=2.0.4+2 <2.0.4+3 depends on rest_client ^2.2.1+9 and rest_client >=2.1.4+8 <2.2.1+11 depends on http ^0.13.5, json_schema2 >=2.0.2+9 <5.1.2 requires http ^0.13.5 or rest_client ^2.2.1+11.
Because no versions of polkadart match >0.4.3 <0.5.0 and polkadart 0.4.3 depends on http ^1.1.0, polkadart ^0.4.3 requires http ^1.1.0.
Thus, if polkadart ^0.4.3 and json_schema2 >=2.0.2+9 <5.1.2 then rest_client ^2.2.1+11.
And because substrate_metadata 1.2.0 depends on json_schema2 ^2.0.2+9, if polkadart ^0.4.3 and substrate_metadata 1.2.0 then rest_client ^2.2.1+11.
And because no versions of substrate_metadata match >1.2.0 <2.0.0 and rest_client >=2.2.1+10 depends on intl ^0.18.1, if polkadart ^0.4.3 and substrate_metadata ^1.2.0 then intl ^0.18.1.
And because taler depends on flutter_localizations from sdk which depends on intl 0.19.0, polkadart ^0.4.3 is incompatible with substrate_metadata ^1.2.0.
So, because taler depends on both polkadart ^0.4.3 and substrate_metadata ^1.2.0, version solving failed.

[✓] Flutter (Channel stable, 3.22.0, on macOS 14.4 23E214 darwin-arm64, locale en-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.89.1)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area
      network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Apple Watch — Степан. Ensure the device is unlocked and discoverable via Bluetooth. (code -27)
[✓] Network resources

**Comment by uddyami** [comment]
I belive this could root cause for my error as well 
```
➜  polkadart git:(main) ✗ dart run packages/polkadart_cli/bin/generate.dart 
Unhandled exception:
ConfigException: Failed to extract config from the 'pubspec.yaml' file.
Can't find 'polkadart' section.
#0      new PubspecConfig.fromYAML (package:polkadart_cli/src/config/pubspec_config.dart:45:7)
#1      new PubspecConfig.fromPubspecFile (package:polkadart_cli/src/config/pubspec_config.dart:30:26)
#2      main (file:///Users/uddyami.agrawal/Raise/polkadart/packages/polkadart_cli/bin/generate.dart:52:32)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by poka-IT** [comment]
I don't have this problem on my stack.

`polkadart` depends on `http` ^1.1.0, while `json_schema2` depends on `http` ^0.13.5 due to `rest_client`; these two versions of `http` are incompatible, indicating that `json_schema2` is outdated.
