### ISSUE TITLE
HttpProvider send jsonrpc error

### ISSUE THREAD

**Issue by gtmickey** [leonardocustodio/polkadart#455]
I think should change http provider  send function like below:

<img width="1212" alt="iShot_2024-06-17_18 30 02" src="https://github.com/leonardocustodio/polkadart/assets/164289762/c13bae73-f879-475f-af0b-4f38210f237f">

date['id'] return as a String  with Vara network, so parse it incase of  failed.

**Comment by leonardocustodio** [comment]
If you can make a PR, it is always welcome :)

**Comment by leonardocustodio** [comment]
This has been fixed at #456 , published to pub.dev under `polkadart: 0.4.4`
