### ISSUE TITLE
Any way I can unify all substrate chains methods over generated fils?

### ISSUE THREAD

**Issue by gtmickey** [leonardocustodio/polkadart#479]
If there are 10 substrate chains like polkadot, kusama, avail, DBC, vara, etc.
I will need to run generate cli and output 10 folders files, most of those files are same, any way I can add it by config or some other way?

**Comment by leonardocustodio** [comment]
Not possible atm. You can though make an interface that will change the "main class" dynamically by checking which network is connected to for example.
