### ISSUE TITLE
how to estimate fee? 

### ISSUE THREAD

**Issue by weishirongzhen** [leonardocustodio/polkadart#500]
I can use json rpc `payment_queryFeeDetails` or `payment_queryInfo ` to query fee before, but I found these two api are error with 
`"data" -> "Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed..."`
now, and I found some doc  about below method, but it looks like polkadart are not contain them?,  any help?

# payment
## queryFeeDetails(extrinsic: Bytes, at?: BlockHash): FeeDetails
- interface: api.rpc.payment.queryFeeDetails
- jsonrpc: payment_queryFeeDetails
- summary: Query the detailed fee of a given encoded extrinsic
- deprecated: Use api.call.transactionPaymentApi.queryFeeDetails instead
## queryInfo(extrinsic: Bytes, at?: BlockHash): RuntimeDispatchInfoV1
- interface: api.rpc.payment.queryInfo
- jsonrpc: payment_queryInfo
- summary: Retrieves the fee information for an encoded extrinsic
- deprecated: Use api.call.transactionPaymentApi.queryInfo instead

**Comment by leonardocustodio** [comment]
You need to send the full encoded extrinsic. You can use a fake signature if you want to do that before really signing it.

**Comment by leonardocustodio** [comment]
Let me know if we can close this one @weishirongzhen

**Comment by weishirongzhen** [comment]
Thanks, sign key issue
